# Generated by Django 4.0.8 on 2022-11-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='email',
            field=models.EmailField(blank=True, default='dfvrn@admin.ru', max_length=254, null=True),
        ),
    ]
