# Generated by Django 4.0.8 on 2022-12-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_feedback_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='option',
            field=models.IntegerField(verbose_name='Тип требуемой помощи'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='type',
            field=models.IntegerField(verbose_name='Тип обращения'),
        ),
    ]
