# Generated by Django 4.0.6 on 2022-07-22 16:21

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_programs_news_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='additional_images',
            field=wagtail.fields.StreamField([('photos', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))], blank=True, null=True, use_json_field=True),
        ),
    ]
