# Generated by Django 4.0.6 on 2022-07-22 22:38

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_news_additional_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='text_down',
            new_name='text_after_photo',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='text_up',
            new_name='text_before_photo',
        ),
        migrations.AlterField(
            model_name='news',
            name='additional_images',
            field=wagtail.fields.StreamField([('photo', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True, use_json_field=None, verbose_name='Фотоотчет'),
        ),
    ]
