# Generated by Django 4.0.6 on 2022-07-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_text_down_news_text_after_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
