# Generated by Django 4.0.8 on 2022-12-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_appeal_options_alter_appeal_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('work', 'В работе'), ('done', 'Выполнен'), ('archive', 'В архиве')], default='new', max_length=50, verbose_name='Статус'),
        ),
    ]
