# Generated by Django 4.0.6 on 2022-08-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_news_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='caption',
            field=models.CharField(max_length=250, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='programs',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='programs',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание программы'),
        ),
        migrations.AddField(
            model_name='programs',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название программы'),
        ),
    ]
