# Generated by Django 4.0.6 on 2022-08-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_programs_caption_programs_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='caption',
            field=models.TextField(null=True, verbose_name='Подпись'),
        ),
    ]
