# Generated by Django 4.0.8 on 2023-01-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_feedback_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
