# Generated by Django 4.0.6 on 2022-08-06 23:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_programs_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(verbose_name='информация о фонде')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='номер телефона')),
                ('second_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='дополнительный номер теелфона')),
                ('email', models.EmailField(max_length=255, verbose_name='адрес электронной почты')),
                ('address', models.TextField(verbose_name='полный адрес')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='home.homepage')),
            ],
        ),
    ]
