# Generated by Django 4.0.6 on 2022-08-08 11:30

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_aboutinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='aboutinfo',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='дополнительный номер теелфона'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='отчёт')),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='home.homepage')),
            ],
        ),
    ]
