# Generated by Django 4.0.8 on 2023-01-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_feedback_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.CheckConstraint(check=models.Q(('type__gte', 1), ('type__lte', 3)), name='appeal_type_constraint'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.CheckConstraint(check=models.Q(('option__gte', 1), ('option__lte', 7)), name='appeal_option_constraint'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.CheckConstraint(check=models.Q(('status', 'new'), ('status', 'work'), ('status', 'done'), ('status', 'archive'), _connector='OR'), name='appeal_status_constraint'),
        ),
    ]
