# Generated by Django 4.0.8 on 2023-01-10 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_appeal_appeal_type_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата обращения'),
            preserve_default=False,
        ),
    ]
