# Generated by Django 4.0.6 on 2022-08-30 14:43

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_partner_feedback_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='page',
            field=modelcluster.fields.ParentalKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.homepage'),
        ),
    ]
