# Generated by Django 4.0.8 on 2023-01-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_appeal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
