# Generated by Django 4.0.8 on 2023-01-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_appeal_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='Важное'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заметка'),
        ),
    ]
