# Generated by Django 4.0.8 on 2023-01-20 09:47

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_appeal_flag_alter_appeal_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.homepage'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Количество звезд'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание программы'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='title',
            field=models.CharField(default='default', max_length=100, verbose_name='Название программы'),
            preserve_default=False,
        ),
    ]
