<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-09-02 10:17
=======
# Generated by Django 4.0.4 on 2022-09-02 11:51
>>>>>>> e53bf4d3dc35fe896be661e97b06f0a24056c0ce

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_stars_feedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=12)),
                ('option', models.IntegerField()),
            ],
        ),
    ]
