# Generated by Django 4.0.8 on 2023-01-22 16:30

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_feedback_page_alter_feedback_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='page',
            field=modelcluster.fields.ParentalKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.homepage'),
        ),
    ]
