# Generated by Django 4.0.8 on 2023-01-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_appeal_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='done_tasks_count',
            field=models.IntegerField(default=0),
        ),
    ]
